addr: 127.0.0.1:50071
name: "1"
kafkacomsumer:
  addr:
    - 127.0.0.1:9092
  topics:
    - laneIM
  groupid: job
etcd:
  addr:
    - 127.0.0.1:2379
redis:
  addr:
    - 127.0.0.1:7001
    - 127.0.0.1:7002
    - 127.0.0.1:7003
bucketsize: 32
cometroutinesize: 32
mysql:
  type: ""
  name: "0"
  username: debian-sys-maint
  password: FJho5xokpFqZygL5
  addr: localhost:3306
  database: laneIM
