// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: proto/msg/msg.proto

package msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgType int32

const (
	MsgType_BRODCAST   MsgType = 0
	MsgType_SINGLE     MsgType = 1
	MsgType_BRODCASTMS MsgType = 2
)

// Enum value maps for MsgType.
var (
	MsgType_name = map[int32]string{
		0: "BRODCAST",
		1: "SINGLE",
		2: "BRODCASTMS",
	}
	MsgType_value = map[string]int32{
		"BRODCAST":   0,
		"SINGLE":     1,
		"BRODCASTMS": 2,
	}
)

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}

func (x MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_msg_msg_proto_enumTypes[0].Descriptor()
}

func (MsgType) Type() protoreflect.EnumType {
	return &file_proto_msg_msg_proto_enumTypes[0]
}

func (x MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgType.Descriptor instead.
func (MsgType) EnumDescriptor() ([]byte, []int) {
	return file_proto_msg_msg_proto_rawDescGZIP(), []int{0}
}

type Msg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Op   MsgType `protobuf:"varint,1,opt,name=op,proto3,enum=lane.msg.MsgType" json:"op,omitempty"`
	Seq  int64   `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Var  int32   `protobuf:"varint,3,opt,name=var,proto3" json:"var,omitempty"`
	Byte []byte  `protobuf:"bytes,4,opt,name=byte,proto3" json:"byte,omitempty"`
}

func (x *Msg) Reset() {
	*x = Msg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_msg_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Msg) ProtoMessage() {}

func (x *Msg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_msg_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Msg.ProtoReflect.Descriptor instead.
func (*Msg) Descriptor() ([]byte, []int) {
	return file_proto_msg_msg_proto_rawDescGZIP(), []int{0}
}

func (x *Msg) GetOp() MsgType {
	if x != nil {
		return x.Op
	}
	return MsgType_BRODCAST
}

func (x *Msg) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Msg) GetVar() int32 {
	if x != nil {
		return x.Var
	}
	return 0
}

func (x *Msg) GetByte() []byte {
	if x != nil {
		return x.Byte
	}
	return nil
}

var File_proto_msg_msg_proto protoreflect.FileDescriptor

var file_proto_msg_msg_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x73, 0x67, 0x2f, 0x6d, 0x73, 0x67, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x6d, 0x73, 0x67, 0x22,
	0x60, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x12, 0x21, 0x0a, 0x02, 0x6f, 0x70, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x11, 0x2e, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x4d, 0x73,
	0x67, 0x54, 0x79, 0x70, 0x65, 0x52, 0x02, 0x6f, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x73, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x76,
	0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x76, 0x61, 0x72, 0x12, 0x12, 0x0a,
	0x04, 0x62, 0x79, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x62, 0x79, 0x74,
	0x65, 0x2a, 0x33, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0c, 0x0a, 0x08,
	0x42, 0x52, 0x4f, 0x44, 0x43, 0x41, 0x53, 0x54, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x49,
	0x4e, 0x47, 0x4c, 0x45, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x42, 0x52, 0x4f, 0x44, 0x43, 0x41,
	0x53, 0x54, 0x4d, 0x53, 0x10, 0x02, 0x42, 0x16, 0x5a, 0x14, 0x6c, 0x61, 0x6e, 0x65, 0x49, 0x4d,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x73, 0x67, 0x3b, 0x6d, 0x73, 0x67, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_msg_msg_proto_rawDescOnce sync.Once
	file_proto_msg_msg_proto_rawDescData = file_proto_msg_msg_proto_rawDesc
)

func file_proto_msg_msg_proto_rawDescGZIP() []byte {
	file_proto_msg_msg_proto_rawDescOnce.Do(func() {
		file_proto_msg_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_msg_msg_proto_rawDescData)
	})
	return file_proto_msg_msg_proto_rawDescData
}

var file_proto_msg_msg_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_msg_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_msg_msg_proto_goTypes = []any{
	(MsgType)(0), // 0: lane.msg.MsgType
	(*Msg)(nil),  // 1: lane.msg.Msg
}
var file_proto_msg_msg_proto_depIdxs = []int32{
	0, // 0: lane.msg.Msg.op:type_name -> lane.msg.MsgType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_msg_msg_proto_init() }
func file_proto_msg_msg_proto_init() {
	if File_proto_msg_msg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_msg_msg_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Msg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_msg_msg_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_msg_msg_proto_goTypes,
		DependencyIndexes: file_proto_msg_msg_proto_depIdxs,
		EnumInfos:         file_proto_msg_msg_proto_enumTypes,
		MessageInfos:      file_proto_msg_msg_proto_msgTypes,
	}.Build()
	File_proto_msg_msg_proto = out.File
	file_proto_msg_msg_proto_rawDesc = nil
	file_proto_msg_msg_proto_goTypes = nil
	file_proto_msg_msg_proto_depIdxs = nil
}
