// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: proto/msg/msg.proto

package msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Msg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Seq  int64  `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
}

func (x *Msg) Reset() {
	*x = Msg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_msg_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Msg) ProtoMessage() {}

func (x *Msg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_msg_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Msg.ProtoReflect.Descriptor instead.
func (*Msg) Descriptor() ([]byte, []int) {
	return file_proto_msg_msg_proto_rawDescGZIP(), []int{0}
}

func (x *Msg) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Msg) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Msg) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type UserInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userid int64           `protobuf:"varint,1,opt,name=userid,proto3" json:"userid,omitempty"`
	Online bool            `protobuf:"varint,2,opt,name=online,proto3" json:"online,omitempty"`
	Roomid map[int64]bool  `protobuf:"bytes,3,rep,name=roomid,proto3" json:"roomid,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Server map[string]bool `protobuf:"bytes,4,rep,name=server,proto3" json:"server,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_msg_msg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_msg_msg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_proto_msg_msg_proto_rawDescGZIP(), []int{1}
}

func (x *UserInfo) GetUserid() int64 {
	if x != nil {
		return x.Userid
	}
	return 0
}

func (x *UserInfo) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *UserInfo) GetRoomid() map[int64]bool {
	if x != nil {
		return x.Roomid
	}
	return nil
}

func (x *UserInfo) GetServer() map[string]bool {
	if x != nil {
		return x.Server
	}
	return nil
}

type RoomInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Roomid    int64           `protobuf:"varint,1,opt,name=roomid,proto3" json:"roomid,omitempty"`
	Server    map[string]bool `protobuf:"bytes,2,rep,name=server,proto3" json:"server,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Users     map[int64]bool  `protobuf:"bytes,3,rep,name=users,proto3" json:"users,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	OnlineNum int64           `protobuf:"varint,4,opt,name=onlineNum,proto3" json:"onlineNum,omitempty"`
}

func (x *RoomInfo) Reset() {
	*x = RoomInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_msg_msg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomInfo) ProtoMessage() {}

func (x *RoomInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_msg_msg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomInfo.ProtoReflect.Descriptor instead.
func (*RoomInfo) Descriptor() ([]byte, []int) {
	return file_proto_msg_msg_proto_rawDescGZIP(), []int{2}
}

func (x *RoomInfo) GetRoomid() int64 {
	if x != nil {
		return x.Roomid
	}
	return 0
}

func (x *RoomInfo) GetServer() map[string]bool {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *RoomInfo) GetUsers() map[int64]bool {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *RoomInfo) GetOnlineNum() int64 {
	if x != nil {
		return x.OnlineNum
	}
	return 0
}

type CAuthReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Params []string `protobuf:"bytes,1,rep,name=params,proto3" json:"params,omitempty"`
	Userid int64    `protobuf:"varint,2,opt,name=userid,proto3" json:"userid,omitempty"`
}

func (x *CAuthReq) Reset() {
	*x = CAuthReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_msg_msg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CAuthReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CAuthReq) ProtoMessage() {}

func (x *CAuthReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_msg_msg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CAuthReq.ProtoReflect.Descriptor instead.
func (*CAuthReq) Descriptor() ([]byte, []int) {
	return file_proto_msg_msg_proto_rawDescGZIP(), []int{3}
}

func (x *CAuthReq) GetParams() []string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *CAuthReq) GetUserid() int64 {
	if x != nil {
		return x.Userid
	}
	return 0
}

type CAuthResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pass bool `protobuf:"varint,1,opt,name=pass,proto3" json:"pass,omitempty"`
}

func (x *CAuthResp) Reset() {
	*x = CAuthResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_msg_msg_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CAuthResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CAuthResp) ProtoMessage() {}

func (x *CAuthResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_msg_msg_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CAuthResp.ProtoReflect.Descriptor instead.
func (*CAuthResp) Descriptor() ([]byte, []int) {
	return file_proto_msg_msg_proto_rawDescGZIP(), []int{4}
}

func (x *CAuthResp) GetPass() bool {
	if x != nil {
		return x.Pass
	}
	return false
}

type CRoomidReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userid int64 `protobuf:"varint,1,opt,name=userid,proto3" json:"userid,omitempty"`
}

func (x *CRoomidReq) Reset() {
	*x = CRoomidReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_msg_msg_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CRoomidReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CRoomidReq) ProtoMessage() {}

func (x *CRoomidReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_msg_msg_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CRoomidReq.ProtoReflect.Descriptor instead.
func (*CRoomidReq) Descriptor() ([]byte, []int) {
	return file_proto_msg_msg_proto_rawDescGZIP(), []int{5}
}

func (x *CRoomidReq) GetUserid() int64 {
	if x != nil {
		return x.Userid
	}
	return 0
}

type CRoomidResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Roomid []int64 `protobuf:"varint,1,rep,packed,name=roomid,proto3" json:"roomid,omitempty"`
}

func (x *CRoomidResp) Reset() {
	*x = CRoomidResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_msg_msg_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CRoomidResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CRoomidResp) ProtoMessage() {}

func (x *CRoomidResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_msg_msg_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CRoomidResp.ProtoReflect.Descriptor instead.
func (*CRoomidResp) Descriptor() ([]byte, []int) {
	return file_proto_msg_msg_proto_rawDescGZIP(), []int{6}
}

func (x *CRoomidResp) GetRoomid() []int64 {
	if x != nil {
		return x.Roomid
	}
	return nil
}

type CSendRoomReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userid int64  `protobuf:"varint,1,opt,name=userid,proto3" json:"userid,omitempty"`
	Roomid int64  `protobuf:"varint,2,opt,name=roomid,proto3" json:"roomid,omitempty"`
	Msg    string `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *CSendRoomReq) Reset() {
	*x = CSendRoomReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_msg_msg_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSendRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSendRoomReq) ProtoMessage() {}

func (x *CSendRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_msg_msg_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSendRoomReq.ProtoReflect.Descriptor instead.
func (*CSendRoomReq) Descriptor() ([]byte, []int) {
	return file_proto_msg_msg_proto_rawDescGZIP(), []int{7}
}

func (x *CSendRoomReq) GetUserid() int64 {
	if x != nil {
		return x.Userid
	}
	return 0
}

func (x *CSendRoomReq) GetRoomid() int64 {
	if x != nil {
		return x.Roomid
	}
	return 0
}

func (x *CSendRoomReq) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type CSendRoomResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ack bool `protobuf:"varint,1,opt,name=ack,proto3" json:"ack,omitempty"`
}

func (x *CSendRoomResp) Reset() {
	*x = CSendRoomResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_msg_msg_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSendRoomResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSendRoomResp) ProtoMessage() {}

func (x *CSendRoomResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_msg_msg_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSendRoomResp.ProtoReflect.Descriptor instead.
func (*CSendRoomResp) Descriptor() ([]byte, []int) {
	return file_proto_msg_msg_proto_rawDescGZIP(), []int{8}
}

func (x *CSendRoomResp) GetAck() bool {
	if x != nil {
		return x.Ack
	}
	return false
}

// offline
type COfflineReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userid int64 `protobuf:"varint,1,opt,name=userid,proto3" json:"userid,omitempty"`
}

func (x *COfflineReq) Reset() {
	*x = COfflineReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_msg_msg_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *COfflineReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*COfflineReq) ProtoMessage() {}

func (x *COfflineReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_msg_msg_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use COfflineReq.ProtoReflect.Descriptor instead.
func (*COfflineReq) Descriptor() ([]byte, []int) {
	return file_proto_msg_msg_proto_rawDescGZIP(), []int{9}
}

func (x *COfflineReq) GetUserid() int64 {
	if x != nil {
		return x.Userid
	}
	return 0
}

type CometInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rooms []int64 `protobuf:"varint,1,rep,packed,name=rooms,proto3" json:"rooms,omitempty"`
}

func (x *CometInfo) Reset() {
	*x = CometInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_msg_msg_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CometInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CometInfo) ProtoMessage() {}

func (x *CometInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_msg_msg_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CometInfo.ProtoReflect.Descriptor instead.
func (*CometInfo) Descriptor() ([]byte, []int) {
	return file_proto_msg_msg_proto_rawDescGZIP(), []int{10}
}

func (x *CometInfo) GetRooms() []int64 {
	if x != nil {
		return x.Rooms
	}
	return nil
}

var File_proto_msg_msg_proto protoreflect.FileDescriptor

var file_proto_msg_msg_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x73, 0x67, 0x2f, 0x6d, 0x73, 0x67, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x6d, 0x73, 0x67, 0x22,
	0x3f, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x10,
	0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x73, 0x65, 0x71,
	0x22, 0xa0, 0x02, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x36, 0x0a,
	0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x69, 0x64, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e,
	0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x69, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x72,
	0x6f, 0x6f, 0x6d, 0x69, 0x64, 0x12, 0x36, 0x0a, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x6d, 0x73, 0x67,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x1a, 0x39, 0x0a,
	0x0b, 0x52, 0x6f, 0x6f, 0x6d, 0x69, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x39, 0x0a, 0x0b, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x22, 0xa2, 0x02, 0x0a, 0x08, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x69, 0x64, 0x12, 0x36, 0x0a, 0x06, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6c, 0x61, 0x6e, 0x65, 0x2e,
	0x6d, 0x73, 0x67, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x12, 0x33, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1d, 0x2e, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x49,
	0x6e, 0x66, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05,
	0x75, 0x73, 0x65, 0x72, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x4e,
	0x75, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65,
	0x4e, 0x75, 0x6d, 0x1a, 0x39, 0x0a, 0x0b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x38,
	0x0a, 0x0a, 0x55, 0x73, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x3a, 0x0a, 0x08, 0x43, 0x41, 0x75, 0x74,
	0x68, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x69, 0x64, 0x22, 0x1f, 0x0a, 0x09, 0x43, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x04, 0x70, 0x61, 0x73, 0x73, 0x22, 0x24, 0x0a, 0x0a, 0x43, 0x52, 0x6f, 0x6f, 0x6d, 0x69, 0x64,
	0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x22, 0x25, 0x0a, 0x0b, 0x43,
	0x52, 0x6f, 0x6f, 0x6d, 0x69, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f,
	0x6f, 0x6d, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d,
	0x69, 0x64, 0x22, 0x50, 0x0a, 0x0c, 0x43, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x6f, 0x6f, 0x6d, 0x52,
	0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f,
	0x6f, 0x6d, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d,
	0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6d, 0x73, 0x67, 0x22, 0x21, 0x0a, 0x0d, 0x43, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x6f, 0x6f,
	0x6d, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x03, 0x61, 0x63, 0x6b, 0x22, 0x25, 0x0a, 0x0b, 0x43, 0x4f, 0x66, 0x66, 0x6c,
	0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x22, 0x21,
	0x0a, 0x09, 0x43, 0x6f, 0x6d, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x72,
	0x6f, 0x6f, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x05, 0x72, 0x6f, 0x6f, 0x6d,
	0x73, 0x42, 0x16, 0x5a, 0x14, 0x6c, 0x61, 0x6e, 0x65, 0x49, 0x4d, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x6d, 0x73, 0x67, 0x3b, 0x6d, 0x73, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_msg_msg_proto_rawDescOnce sync.Once
	file_proto_msg_msg_proto_rawDescData = file_proto_msg_msg_proto_rawDesc
)

func file_proto_msg_msg_proto_rawDescGZIP() []byte {
	file_proto_msg_msg_proto_rawDescOnce.Do(func() {
		file_proto_msg_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_msg_msg_proto_rawDescData)
	})
	return file_proto_msg_msg_proto_rawDescData
}

var file_proto_msg_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_msg_msg_proto_goTypes = []any{
	(*Msg)(nil),           // 0: lane.msg.Msg
	(*UserInfo)(nil),      // 1: lane.msg.UserInfo
	(*RoomInfo)(nil),      // 2: lane.msg.RoomInfo
	(*CAuthReq)(nil),      // 3: lane.msg.CAuthReq
	(*CAuthResp)(nil),     // 4: lane.msg.CAuthResp
	(*CRoomidReq)(nil),    // 5: lane.msg.CRoomidReq
	(*CRoomidResp)(nil),   // 6: lane.msg.CRoomidResp
	(*CSendRoomReq)(nil),  // 7: lane.msg.CSendRoomReq
	(*CSendRoomResp)(nil), // 8: lane.msg.CSendRoomResp
	(*COfflineReq)(nil),   // 9: lane.msg.COfflineReq
	(*CometInfo)(nil),     // 10: lane.msg.CometInfo
	nil,                   // 11: lane.msg.UserInfo.RoomidEntry
	nil,                   // 12: lane.msg.UserInfo.ServerEntry
	nil,                   // 13: lane.msg.RoomInfo.ServerEntry
	nil,                   // 14: lane.msg.RoomInfo.UsersEntry
}
var file_proto_msg_msg_proto_depIdxs = []int32{
	11, // 0: lane.msg.UserInfo.roomid:type_name -> lane.msg.UserInfo.RoomidEntry
	12, // 1: lane.msg.UserInfo.server:type_name -> lane.msg.UserInfo.ServerEntry
	13, // 2: lane.msg.RoomInfo.server:type_name -> lane.msg.RoomInfo.ServerEntry
	14, // 3: lane.msg.RoomInfo.users:type_name -> lane.msg.RoomInfo.UsersEntry
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_msg_msg_proto_init() }
func file_proto_msg_msg_proto_init() {
	if File_proto_msg_msg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_msg_msg_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Msg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_msg_msg_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*UserInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_msg_msg_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*RoomInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_msg_msg_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*CAuthReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_msg_msg_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*CAuthResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_msg_msg_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*CRoomidReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_msg_msg_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*CRoomidResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_msg_msg_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*CSendRoomReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_msg_msg_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*CSendRoomResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_msg_msg_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*COfflineReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_msg_msg_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*CometInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_msg_msg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_msg_msg_proto_goTypes,
		DependencyIndexes: file_proto_msg_msg_proto_depIdxs,
		MessageInfos:      file_proto_msg_msg_proto_msgTypes,
	}.Build()
	File_proto_msg_msg_proto = out.File
	file_proto_msg_msg_proto_rawDesc = nil
	file_proto_msg_msg_proto_goTypes = nil
	file_proto_msg_msg_proto_depIdxs = nil
}
