// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: proto/logic/logic.proto

package logic

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	msg "laneIM/proto/msg"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NoReq) Reset() {
	*x = NoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_logic_logic_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoReq) ProtoMessage() {}

func (x *NoReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_logic_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoReq.ProtoReflect.Descriptor instead.
func (*NoReq) Descriptor() ([]byte, []int) {
	return file_proto_logic_logic_proto_rawDescGZIP(), []int{0}
}

type NoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NoResp) Reset() {
	*x = NoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_logic_logic_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoResp) ProtoMessage() {}

func (x *NoResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_logic_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoResp.ProtoReflect.Descriptor instead.
func (*NoResp) Descriptor() ([]byte, []int) {
	return file_proto_logic_logic_proto_rawDescGZIP(), []int{1}
}

type SetOnlineReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userid int64  `protobuf:"varint,1,opt,name=userid,proto3" json:"userid,omitempty"`
	Server string `protobuf:"bytes,2,opt,name=server,proto3" json:"server,omitempty"`
}

func (x *SetOnlineReq) Reset() {
	*x = SetOnlineReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_logic_logic_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetOnlineReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetOnlineReq) ProtoMessage() {}

func (x *SetOnlineReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_logic_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetOnlineReq.ProtoReflect.Descriptor instead.
func (*SetOnlineReq) Descriptor() ([]byte, []int) {
	return file_proto_logic_logic_proto_rawDescGZIP(), []int{2}
}

func (x *SetOnlineReq) GetUserid() int64 {
	if x != nil {
		return x.Userid
	}
	return 0
}

func (x *SetOnlineReq) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

type SetOnlineResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetOnlineResp) Reset() {
	*x = SetOnlineResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_logic_logic_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetOnlineResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetOnlineResp) ProtoMessage() {}

func (x *SetOnlineResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_logic_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetOnlineResp.ProtoReflect.Descriptor instead.
func (*SetOnlineResp) Descriptor() ([]byte, []int) {
	return file_proto_logic_logic_proto_rawDescGZIP(), []int{3}
}

type SetOnlineBatchReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userid []int64 `protobuf:"varint,1,rep,packed,name=userid,proto3" json:"userid,omitempty"`
	Server string  `protobuf:"bytes,2,opt,name=server,proto3" json:"server,omitempty"`
}

func (x *SetOnlineBatchReq) Reset() {
	*x = SetOnlineBatchReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_logic_logic_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetOnlineBatchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetOnlineBatchReq) ProtoMessage() {}

func (x *SetOnlineBatchReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_logic_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetOnlineBatchReq.ProtoReflect.Descriptor instead.
func (*SetOnlineBatchReq) Descriptor() ([]byte, []int) {
	return file_proto_logic_logic_proto_rawDescGZIP(), []int{4}
}

func (x *SetOnlineBatchReq) GetUserid() []int64 {
	if x != nil {
		return x.Userid
	}
	return nil
}

func (x *SetOnlineBatchReq) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

type SetOnlineBatchResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetOnlineBatchResp) Reset() {
	*x = SetOnlineBatchResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_logic_logic_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetOnlineBatchResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetOnlineBatchResp) ProtoMessage() {}

func (x *SetOnlineBatchResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_logic_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetOnlineBatchResp.ProtoReflect.Descriptor instead.
func (*SetOnlineBatchResp) Descriptor() ([]byte, []int) {
	return file_proto_logic_logic_proto_rawDescGZIP(), []int{5}
}

type SetOfflineReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userid int64  `protobuf:"varint,1,opt,name=userid,proto3" json:"userid,omitempty"`
	Server string `protobuf:"bytes,2,opt,name=server,proto3" json:"server,omitempty"`
}

func (x *SetOfflineReq) Reset() {
	*x = SetOfflineReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_logic_logic_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetOfflineReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetOfflineReq) ProtoMessage() {}

func (x *SetOfflineReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_logic_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetOfflineReq.ProtoReflect.Descriptor instead.
func (*SetOfflineReq) Descriptor() ([]byte, []int) {
	return file_proto_logic_logic_proto_rawDescGZIP(), []int{6}
}

func (x *SetOfflineReq) GetUserid() int64 {
	if x != nil {
		return x.Userid
	}
	return 0
}

func (x *SetOfflineReq) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

type SetOfflineBatchReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userid []int64 `protobuf:"varint,1,rep,packed,name=userid,proto3" json:"userid,omitempty"`
	Server string  `protobuf:"bytes,2,opt,name=server,proto3" json:"server,omitempty"`
}

func (x *SetOfflineBatchReq) Reset() {
	*x = SetOfflineBatchReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_logic_logic_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetOfflineBatchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetOfflineBatchReq) ProtoMessage() {}

func (x *SetOfflineBatchReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_logic_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetOfflineBatchReq.ProtoReflect.Descriptor instead.
func (*SetOfflineBatchReq) Descriptor() ([]byte, []int) {
	return file_proto_logic_logic_proto_rawDescGZIP(), []int{7}
}

func (x *SetOfflineBatchReq) GetUserid() []int64 {
	if x != nil {
		return x.Userid
	}
	return nil
}

func (x *SetOfflineBatchReq) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

type JoinRoomReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userid int64 `protobuf:"varint,1,opt,name=userid,proto3" json:"userid,omitempty"`
	Roomid int64 `protobuf:"varint,3,opt,name=roomid,proto3" json:"roomid,omitempty"`
}

func (x *JoinRoomReq) Reset() {
	*x = JoinRoomReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_logic_logic_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomReq) ProtoMessage() {}

func (x *JoinRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_logic_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomReq.ProtoReflect.Descriptor instead.
func (*JoinRoomReq) Descriptor() ([]byte, []int) {
	return file_proto_logic_logic_proto_rawDescGZIP(), []int{8}
}

func (x *JoinRoomReq) GetUserid() int64 {
	if x != nil {
		return x.Userid
	}
	return 0
}

func (x *JoinRoomReq) GetRoomid() int64 {
	if x != nil {
		return x.Roomid
	}
	return 0
}

type JoinRoomBatchReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Comet  string  `protobuf:"bytes,1,opt,name=comet,proto3" json:"comet,omitempty"`
	Userid []int64 `protobuf:"varint,2,rep,packed,name=userid,proto3" json:"userid,omitempty"`
	Roomid []int64 `protobuf:"varint,3,rep,packed,name=roomid,proto3" json:"roomid,omitempty"`
}

func (x *JoinRoomBatchReq) Reset() {
	*x = JoinRoomBatchReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_logic_logic_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinRoomBatchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomBatchReq) ProtoMessage() {}

func (x *JoinRoomBatchReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_logic_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomBatchReq.ProtoReflect.Descriptor instead.
func (*JoinRoomBatchReq) Descriptor() ([]byte, []int) {
	return file_proto_logic_logic_proto_rawDescGZIP(), []int{9}
}

func (x *JoinRoomBatchReq) GetComet() string {
	if x != nil {
		return x.Comet
	}
	return ""
}

func (x *JoinRoomBatchReq) GetUserid() []int64 {
	if x != nil {
		return x.Userid
	}
	return nil
}

func (x *JoinRoomBatchReq) GetRoomid() []int64 {
	if x != nil {
		return x.Roomid
	}
	return nil
}

type QuitRoomReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userid int64 `protobuf:"varint,1,opt,name=userid,proto3" json:"userid,omitempty"`
	Roomid int64 `protobuf:"varint,2,opt,name=roomid,proto3" json:"roomid,omitempty"`
}

func (x *QuitRoomReq) Reset() {
	*x = QuitRoomReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_logic_logic_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuitRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuitRoomReq) ProtoMessage() {}

func (x *QuitRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_logic_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuitRoomReq.ProtoReflect.Descriptor instead.
func (*QuitRoomReq) Descriptor() ([]byte, []int) {
	return file_proto_logic_logic_proto_rawDescGZIP(), []int{10}
}

func (x *QuitRoomReq) GetUserid() int64 {
	if x != nil {
		return x.Userid
	}
	return 0
}

func (x *QuitRoomReq) GetRoomid() int64 {
	if x != nil {
		return x.Roomid
	}
	return 0
}

type QueryRoomReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userid []int64 `protobuf:"varint,1,rep,packed,name=userid,proto3" json:"userid,omitempty"`
}

func (x *QueryRoomReq) Reset() {
	*x = QueryRoomReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_logic_logic_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRoomReq) ProtoMessage() {}

func (x *QueryRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_logic_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRoomReq.ProtoReflect.Descriptor instead.
func (*QueryRoomReq) Descriptor() ([]byte, []int) {
	return file_proto_logic_logic_proto_rawDescGZIP(), []int{11}
}

func (x *QueryRoomReq) GetUserid() []int64 {
	if x != nil {
		return x.Userid
	}
	return nil
}

type QueryRoomResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Roomids []*QueryRoomResp_RoomSlice `protobuf:"bytes,1,rep,name=roomids,proto3" json:"roomids,omitempty"`
}

func (x *QueryRoomResp) Reset() {
	*x = QueryRoomResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_logic_logic_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryRoomResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRoomResp) ProtoMessage() {}

func (x *QueryRoomResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_logic_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRoomResp.ProtoReflect.Descriptor instead.
func (*QueryRoomResp) Descriptor() ([]byte, []int) {
	return file_proto_logic_logic_proto_rawDescGZIP(), []int{12}
}

func (x *QueryRoomResp) GetRoomids() []*QueryRoomResp_RoomSlice {
	if x != nil {
		return x.Roomids
	}
	return nil
}

type QueryServerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userid []int64 `protobuf:"varint,1,rep,packed,name=userid,proto3" json:"userid,omitempty"`
}

func (x *QueryServerReq) Reset() {
	*x = QueryServerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_logic_logic_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryServerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryServerReq) ProtoMessage() {}

func (x *QueryServerReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_logic_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryServerReq.ProtoReflect.Descriptor instead.
func (*QueryServerReq) Descriptor() ([]byte, []int) {
	return file_proto_logic_logic_proto_rawDescGZIP(), []int{13}
}

func (x *QueryServerReq) GetUserid() []int64 {
	if x != nil {
		return x.Userid
	}
	return nil
}

type QueryServerResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserinfoResp []*QueryServerResp_UserInfoResp `protobuf:"bytes,1,rep,name=userinfoResp,proto3" json:"userinfoResp,omitempty"`
}

func (x *QueryServerResp) Reset() {
	*x = QueryServerResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_logic_logic_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryServerResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryServerResp) ProtoMessage() {}

func (x *QueryServerResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_logic_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryServerResp.ProtoReflect.Descriptor instead.
func (*QueryServerResp) Descriptor() ([]byte, []int) {
	return file_proto_logic_logic_proto_rawDescGZIP(), []int{14}
}

func (x *QueryServerResp) GetUserinfoResp() []*QueryServerResp_UserInfoResp {
	if x != nil {
		return x.UserinfoResp
	}
	return nil
}

type NewUserReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NewUserReq) Reset() {
	*x = NewUserReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_logic_logic_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewUserReq) ProtoMessage() {}

func (x *NewUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_logic_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewUserReq.ProtoReflect.Descriptor instead.
func (*NewUserReq) Descriptor() ([]byte, []int) {
	return file_proto_logic_logic_proto_rawDescGZIP(), []int{15}
}

type NewUserResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userid int64 `protobuf:"varint,1,opt,name=userid,proto3" json:"userid,omitempty"`
}

func (x *NewUserResp) Reset() {
	*x = NewUserResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_logic_logic_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewUserResp) ProtoMessage() {}

func (x *NewUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_logic_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewUserResp.ProtoReflect.Descriptor instead.
func (*NewUserResp) Descriptor() ([]byte, []int) {
	return file_proto_logic_logic_proto_rawDescGZIP(), []int{16}
}

func (x *NewUserResp) GetUserid() int64 {
	if x != nil {
		return x.Userid
	}
	return 0
}

type NewUserBatchReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *NewUserBatchReq) Reset() {
	*x = NewUserBatchReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_logic_logic_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewUserBatchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewUserBatchReq) ProtoMessage() {}

func (x *NewUserBatchReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_logic_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewUserBatchReq.ProtoReflect.Descriptor instead.
func (*NewUserBatchReq) Descriptor() ([]byte, []int) {
	return file_proto_logic_logic_proto_rawDescGZIP(), []int{17}
}

func (x *NewUserBatchReq) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type NewUserBatchResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userid []int64 `protobuf:"varint,1,rep,packed,name=userid,proto3" json:"userid,omitempty"`
}

func (x *NewUserBatchResp) Reset() {
	*x = NewUserBatchResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_logic_logic_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewUserBatchResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewUserBatchResp) ProtoMessage() {}

func (x *NewUserBatchResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_logic_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewUserBatchResp.ProtoReflect.Descriptor instead.
func (*NewUserBatchResp) Descriptor() ([]byte, []int) {
	return file_proto_logic_logic_proto_rawDescGZIP(), []int{18}
}

func (x *NewUserBatchResp) GetUserid() []int64 {
	if x != nil {
		return x.Userid
	}
	return nil
}

type NewRoomReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userid    int64  `protobuf:"varint,1,opt,name=userid,proto3" json:"userid,omitempty"`
	CometAddr string `protobuf:"bytes,2,opt,name=cometAddr,proto3" json:"cometAddr,omitempty"`
}

func (x *NewRoomReq) Reset() {
	*x = NewRoomReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_logic_logic_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewRoomReq) ProtoMessage() {}

func (x *NewRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_logic_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewRoomReq.ProtoReflect.Descriptor instead.
func (*NewRoomReq) Descriptor() ([]byte, []int) {
	return file_proto_logic_logic_proto_rawDescGZIP(), []int{19}
}

func (x *NewRoomReq) GetUserid() int64 {
	if x != nil {
		return x.Userid
	}
	return 0
}

func (x *NewRoomReq) GetCometAddr() string {
	if x != nil {
		return x.CometAddr
	}
	return ""
}

type NewRoomResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Roomid int64 `protobuf:"varint,1,opt,name=roomid,proto3" json:"roomid,omitempty"`
}

func (x *NewRoomResp) Reset() {
	*x = NewRoomResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_logic_logic_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewRoomResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewRoomResp) ProtoMessage() {}

func (x *NewRoomResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_logic_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewRoomResp.ProtoReflect.Descriptor instead.
func (*NewRoomResp) Descriptor() ([]byte, []int) {
	return file_proto_logic_logic_proto_rawDescGZIP(), []int{20}
}

func (x *NewRoomResp) GetRoomid() int64 {
	if x != nil {
		return x.Roomid
	}
	return 0
}

type DelUserReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userid int64 `protobuf:"varint,1,opt,name=userid,proto3" json:"userid,omitempty"`
}

func (x *DelUserReq) Reset() {
	*x = DelUserReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_logic_logic_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelUserReq) ProtoMessage() {}

func (x *DelUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_logic_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelUserReq.ProtoReflect.Descriptor instead.
func (*DelUserReq) Descriptor() ([]byte, []int) {
	return file_proto_logic_logic_proto_rawDescGZIP(), []int{21}
}

func (x *DelUserReq) GetUserid() int64 {
	if x != nil {
		return x.Userid
	}
	return 0
}

type AuthReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Params    []string `protobuf:"bytes,1,rep,name=params,proto3" json:"params,omitempty"`
	Userid    int64    `protobuf:"varint,2,opt,name=userid,proto3" json:"userid,omitempty"`
	CometAddr string   `protobuf:"bytes,3,opt,name=cometAddr,proto3" json:"cometAddr,omitempty"`
}

func (x *AuthReq) Reset() {
	*x = AuthReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_logic_logic_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthReq) ProtoMessage() {}

func (x *AuthReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_logic_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthReq.ProtoReflect.Descriptor instead.
func (*AuthReq) Descriptor() ([]byte, []int) {
	return file_proto_logic_logic_proto_rawDescGZIP(), []int{22}
}

func (x *AuthReq) GetParams() []string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *AuthReq) GetUserid() int64 {
	if x != nil {
		return x.Userid
	}
	return 0
}

func (x *AuthReq) GetCometAddr() string {
	if x != nil {
		return x.CometAddr
	}
	return ""
}

type AuthResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pass bool `protobuf:"varint,1,opt,name=pass,proto3" json:"pass,omitempty"`
}

func (x *AuthResp) Reset() {
	*x = AuthResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_logic_logic_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResp) ProtoMessage() {}

func (x *AuthResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_logic_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResp.ProtoReflect.Descriptor instead.
func (*AuthResp) Descriptor() ([]byte, []int) {
	return file_proto_logic_logic_proto_rawDescGZIP(), []int{23}
}

func (x *AuthResp) GetPass() bool {
	if x != nil {
		return x.Pass
	}
	return false
}

type QueryLastReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Roomid []int64 `protobuf:"varint,1,rep,packed,name=roomid,proto3" json:"roomid,omitempty"`
}

func (x *QueryLastReq) Reset() {
	*x = QueryLastReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_logic_logic_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryLastReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryLastReq) ProtoMessage() {}

func (x *QueryLastReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_logic_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryLastReq.ProtoReflect.Descriptor instead.
func (*QueryLastReq) Descriptor() ([]byte, []int) {
	return file_proto_logic_logic_proto_rawDescGZIP(), []int{24}
}

func (x *QueryLastReq) GetRoomid() []int64 {
	if x != nil {
		return x.Roomid
	}
	return nil
}

type QueryLastRelpy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageId []int64 `protobuf:"varint,1,rep,packed,name=messageId,proto3" json:"messageId,omitempty"`
}

func (x *QueryLastRelpy) Reset() {
	*x = QueryLastRelpy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_logic_logic_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryLastRelpy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryLastRelpy) ProtoMessage() {}

func (x *QueryLastRelpy) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_logic_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryLastRelpy.ProtoReflect.Descriptor instead.
func (*QueryLastRelpy) Descriptor() ([]byte, []int) {
	return file_proto_logic_logic_proto_rawDescGZIP(), []int{25}
}

func (x *QueryLastRelpy) GetMessageId() []int64 {
	if x != nil {
		return x.MessageId
	}
	return nil
}

type QueryRoomResp_RoomSlice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Roomid []int64 `protobuf:"varint,1,rep,packed,name=roomid,proto3" json:"roomid,omitempty"`
}

func (x *QueryRoomResp_RoomSlice) Reset() {
	*x = QueryRoomResp_RoomSlice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_logic_logic_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryRoomResp_RoomSlice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRoomResp_RoomSlice) ProtoMessage() {}

func (x *QueryRoomResp_RoomSlice) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_logic_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRoomResp_RoomSlice.ProtoReflect.Descriptor instead.
func (*QueryRoomResp_RoomSlice) Descriptor() ([]byte, []int) {
	return file_proto_logic_logic_proto_rawDescGZIP(), []int{12, 0}
}

func (x *QueryRoomResp_RoomSlice) GetRoomid() []int64 {
	if x != nil {
		return x.Roomid
	}
	return nil
}

type QueryServerResp_UserInfoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Online bool `protobuf:"varint,1,opt,name=online,proto3" json:"online,omitempty"`
	// userinfo的设备可以设置成-1，然后查询所有设备所在服务器id
	ServerAddrs []string `protobuf:"bytes,2,rep,name=serverAddrs,proto3" json:"serverAddrs,omitempty"`
}

func (x *QueryServerResp_UserInfoResp) Reset() {
	*x = QueryServerResp_UserInfoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_logic_logic_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryServerResp_UserInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryServerResp_UserInfoResp) ProtoMessage() {}

func (x *QueryServerResp_UserInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_logic_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryServerResp_UserInfoResp.ProtoReflect.Descriptor instead.
func (*QueryServerResp_UserInfoResp) Descriptor() ([]byte, []int) {
	return file_proto_logic_logic_proto_rawDescGZIP(), []int{14, 0}
}

func (x *QueryServerResp_UserInfoResp) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *QueryServerResp_UserInfoResp) GetServerAddrs() []string {
	if x != nil {
		return x.ServerAddrs
	}
	return nil
}

var File_proto_logic_logic_proto protoreflect.FileDescriptor

var file_proto_logic_logic_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2f, 0x6c, 0x6f,
	0x67, 0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x6c, 0x61, 0x6e, 0x65, 0x2e,
	0x6c, 0x6f, 0x67, 0x69, 0x63, 0x1a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x73, 0x67,
	0x2f, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x07, 0x0a, 0x05, 0x4e, 0x6f,
	0x52, 0x65, 0x71, 0x22, 0x08, 0x0a, 0x06, 0x4e, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x22, 0x3e, 0x0a,
	0x0c, 0x53, 0x65, 0x74, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x22, 0x0f, 0x0a,
	0x0d, 0x53, 0x65, 0x74, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x43,
	0x0a, 0x11, 0x53, 0x65, 0x74, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x42, 0x61, 0x74, 0x63, 0x68,
	0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x22, 0x14, 0x0a, 0x12, 0x53, 0x65, 0x74, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65,
	0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x22, 0x3f, 0x0a, 0x0d, 0x53, 0x65, 0x74,
	0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x22, 0x44, 0x0a, 0x12, 0x53, 0x65,
	0x74, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71,
	0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x22, 0x3d, 0x0a, 0x0b, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x12,
	0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x69, 0x64, 0x22,
	0x58, 0x0a, 0x10, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x42, 0x61, 0x74, 0x63, 0x68,
	0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x6d, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x63, 0x6f, 0x6d, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x69, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x69, 0x64, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x03, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x69, 0x64, 0x22, 0x3d, 0x0a, 0x0b, 0x51, 0x75, 0x69,
	0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x69, 0x64, 0x22, 0x26, 0x0a, 0x0c, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64,
	0x22, 0x73, 0x0a, 0x0d, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x3d, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x23, 0x2e, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x52, 0x6f,
	0x6f, 0x6d, 0x53, 0x6c, 0x69, 0x63, 0x65, 0x52, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x69, 0x64, 0x73,
	0x1a, 0x23, 0x0a, 0x09, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x6c, 0x69, 0x63, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x06, 0x72,
	0x6f, 0x6f, 0x6d, 0x69, 0x64, 0x22, 0x28, 0x0a, 0x0e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x22,
	0xa9, 0x01, 0x0a, 0x0f, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x4c, 0x0a, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x69, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x73, 0x70, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x6c, 0x61, 0x6e, 0x65,
	0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x73, 0x70, 0x52, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x69, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73,
	0x70, 0x1a, 0x48, 0x0a, 0x0c, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x06, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x73, 0x22, 0x0c, 0x0a, 0x0a, 0x4e,
	0x65, 0x77, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x22, 0x25, 0x0a, 0x0b, 0x4e, 0x65, 0x77,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64,
	0x22, 0x27, 0x0a, 0x0f, 0x4e, 0x65, 0x77, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x74, 0x63, 0x68,
	0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x2a, 0x0a, 0x10, 0x4e, 0x65, 0x77,
	0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x69, 0x64, 0x22, 0x42, 0x0a, 0x0a, 0x4e, 0x65, 0x77, 0x52, 0x6f, 0x6f, 0x6d,
	0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x63,
	0x6f, 0x6d, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x63, 0x6f, 0x6d, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x22, 0x25, 0x0a, 0x0b, 0x4e, 0x65, 0x77,
	0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x69, 0x64,
	0x22, 0x24, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x16,
	0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x22, 0x57, 0x0a, 0x07, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65,
	0x71, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69,
	0x64, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x22,
	0x1e, 0x0a, 0x08, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x61, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x70, 0x61, 0x73, 0x73, 0x22,
	0x26, 0x0a, 0x0c, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4c, 0x61, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52,
	0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x69, 0x64, 0x22, 0x2e, 0x0a, 0x0e, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x4c, 0x61, 0x73, 0x74, 0x52, 0x65, 0x6c, 0x70, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x09, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x32, 0x8a, 0x09, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69,
	0x63, 0x12, 0x33, 0x0a, 0x07, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x73, 0x67, 0x12, 0x14, 0x2e, 0x6c,
	0x61, 0x6e, 0x65, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x73, 0x67, 0x52,
	0x65, 0x71, 0x1a, 0x12, 0x2e, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e,
	0x4e, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3d, 0x0a, 0x0c, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x73,
	0x67, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x19, 0x2e, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x6d, 0x73,
	0x67, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x73, 0x67, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65,
	0x71, 0x1a, 0x12, 0x2e, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x4e,
	0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x41, 0x0a, 0x09, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4c, 0x61,
	0x73, 0x74, 0x12, 0x18, 0x2e, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x4c, 0x61, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x6c,
	0x61, 0x6e, 0x65, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4c,
	0x61, 0x73, 0x74, 0x52, 0x65, 0x6c, 0x70, 0x79, 0x12, 0x5a, 0x0a, 0x12, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x4d, 0x73, 0x67, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x20,
	0x2e, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4d,
	0x75, 0x6c, 0x74, 0x69, 0x52, 0x6f, 0x6f, 0x6d, 0x50, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x71,
	0x1a, 0x22, 0x2e, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x52, 0x6f, 0x6f, 0x6d, 0x50, 0x61, 0x67, 0x65, 0x73, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x39, 0x0a, 0x09, 0x53, 0x65, 0x74, 0x4f, 0x6e, 0x6c, 0x69, 0x6e,
	0x65, 0x12, 0x18, 0x2e, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x53,
	0x65, 0x74, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x6c, 0x61,
	0x6e, 0x65, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x4e, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x43, 0x0a, 0x0e, 0x53, 0x65, 0x74, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x42, 0x61, 0x74, 0x63,
	0x68, 0x12, 0x1d, 0x2e, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x53,
	0x65, 0x74, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71,
	0x1a, 0x12, 0x2e, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x4e, 0x6f,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x3b, 0x0a, 0x0a, 0x53, 0x65, 0x74, 0x4f, 0x66, 0x66, 0x6c, 0x69,
	0x6e, 0x65, 0x12, 0x19, 0x2e, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e,
	0x53, 0x65, 0x74, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e,
	0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x4e, 0x6f, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x45, 0x0a, 0x0f, 0x53, 0x65, 0x74, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x42,
	0x61, 0x74, 0x63, 0x68, 0x12, 0x1e, 0x2e, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x6c, 0x6f, 0x67, 0x69,
	0x63, 0x2e, 0x53, 0x65, 0x74, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x42, 0x61, 0x74, 0x63,
	0x68, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x6c, 0x6f, 0x67, 0x69,
	0x63, 0x2e, 0x4e, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3a, 0x0a, 0x07, 0x4e, 0x65, 0x77, 0x55,
	0x73, 0x65, 0x72, 0x12, 0x16, 0x2e, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63,
	0x2e, 0x4e, 0x65, 0x77, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x6c, 0x61,
	0x6e, 0x65, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x4e, 0x65, 0x77, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x49, 0x0a, 0x0c, 0x4e, 0x65, 0x77, 0x55, 0x73, 0x65, 0x72, 0x42,
	0x61, 0x74, 0x63, 0x68, 0x12, 0x1b, 0x2e, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x6c, 0x6f, 0x67, 0x69,
	0x63, 0x2e, 0x4e, 0x65, 0x77, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65,
	0x71, 0x1a, 0x1c, 0x2e, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x4e,
	0x65, 0x77, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x35, 0x0a, 0x07, 0x44, 0x65, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x12, 0x16, 0x2e, 0x6c, 0x61, 0x6e,
	0x65, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x44, 0x65, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x1a, 0x12, 0x2e, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e,
	0x4e, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3a, 0x0a, 0x07, 0x4e, 0x65, 0x77, 0x52, 0x6f, 0x6f,
	0x6d, 0x12, 0x16, 0x2e, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x4e,
	0x65, 0x77, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x6c, 0x61, 0x6e, 0x65,
	0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x4e, 0x65, 0x77, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x37, 0x0a, 0x08, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x17,
	0x2e, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x4a, 0x6f, 0x69, 0x6e,
	0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x6c,
	0x6f, 0x67, 0x69, 0x63, 0x2e, 0x4e, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x41, 0x0a, 0x0d, 0x4a,
	0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x1c, 0x2e, 0x6c,
	0x61, 0x6e, 0x65, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f,
	0x6f, 0x6d, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x6c, 0x61, 0x6e,
	0x65, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x4e, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x37,
	0x0a, 0x08, 0x51, 0x75, 0x69, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x17, 0x2e, 0x6c, 0x61, 0x6e,
	0x65, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x51, 0x75, 0x69, 0x74, 0x52, 0x6f, 0x6f, 0x6d,
	0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63,
	0x2e, 0x4e, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x40, 0x0a, 0x09, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x18, 0x2e, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x6c, 0x6f, 0x67, 0x69,
	0x63, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x1a, 0x19,
	0x2e, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x12, 0x46, 0x0a, 0x0b, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x1a, 0x2e, 0x6c, 0x61, 0x6e, 0x65, 0x2e,
	0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x6c, 0x6f, 0x67, 0x69,
	0x63, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x31, 0x0a, 0x04, 0x41, 0x75, 0x74, 0x68, 0x12, 0x13, 0x2e, 0x6c, 0x61, 0x6e, 0x65,
	0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x71, 0x1a, 0x14,
	0x2e, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x41, 0x75, 0x74, 0x68,
	0x52, 0x65, 0x73, 0x70, 0x42, 0x1a, 0x5a, 0x18, 0x6c, 0x61, 0x6e, 0x65, 0x49, 0x4d, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x3b, 0x6c, 0x6f, 0x67, 0x69, 0x63,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_logic_logic_proto_rawDescOnce sync.Once
	file_proto_logic_logic_proto_rawDescData = file_proto_logic_logic_proto_rawDesc
)

func file_proto_logic_logic_proto_rawDescGZIP() []byte {
	file_proto_logic_logic_proto_rawDescOnce.Do(func() {
		file_proto_logic_logic_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_logic_logic_proto_rawDescData)
	})
	return file_proto_logic_logic_proto_rawDescData
}

var file_proto_logic_logic_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_proto_logic_logic_proto_goTypes = []any{
	(*NoReq)(nil),                        // 0: lane.logic.NoReq
	(*NoResp)(nil),                       // 1: lane.logic.NoResp
	(*SetOnlineReq)(nil),                 // 2: lane.logic.SetOnlineReq
	(*SetOnlineResp)(nil),                // 3: lane.logic.SetOnlineResp
	(*SetOnlineBatchReq)(nil),            // 4: lane.logic.SetOnlineBatchReq
	(*SetOnlineBatchResp)(nil),           // 5: lane.logic.SetOnlineBatchResp
	(*SetOfflineReq)(nil),                // 6: lane.logic.SetOfflineReq
	(*SetOfflineBatchReq)(nil),           // 7: lane.logic.SetOfflineBatchReq
	(*JoinRoomReq)(nil),                  // 8: lane.logic.JoinRoomReq
	(*JoinRoomBatchReq)(nil),             // 9: lane.logic.JoinRoomBatchReq
	(*QuitRoomReq)(nil),                  // 10: lane.logic.QuitRoomReq
	(*QueryRoomReq)(nil),                 // 11: lane.logic.QueryRoomReq
	(*QueryRoomResp)(nil),                // 12: lane.logic.QueryRoomResp
	(*QueryServerReq)(nil),               // 13: lane.logic.QueryServerReq
	(*QueryServerResp)(nil),              // 14: lane.logic.QueryServerResp
	(*NewUserReq)(nil),                   // 15: lane.logic.NewUserReq
	(*NewUserResp)(nil),                  // 16: lane.logic.NewUserResp
	(*NewUserBatchReq)(nil),              // 17: lane.logic.NewUserBatchReq
	(*NewUserBatchResp)(nil),             // 18: lane.logic.NewUserBatchResp
	(*NewRoomReq)(nil),                   // 19: lane.logic.NewRoomReq
	(*NewRoomResp)(nil),                  // 20: lane.logic.NewRoomResp
	(*DelUserReq)(nil),                   // 21: lane.logic.DelUserReq
	(*AuthReq)(nil),                      // 22: lane.logic.AuthReq
	(*AuthResp)(nil),                     // 23: lane.logic.AuthResp
	(*QueryLastReq)(nil),                 // 24: lane.logic.QueryLastReq
	(*QueryLastRelpy)(nil),               // 25: lane.logic.QueryLastRelpy
	(*QueryRoomResp_RoomSlice)(nil),      // 26: lane.logic.QueryRoomResp.RoomSlice
	(*QueryServerResp_UserInfoResp)(nil), // 27: lane.logic.QueryServerResp.UserInfoResp
	(*msg.SendMsgReq)(nil),               // 28: lane.msg.SendMsgReq
	(*msg.SendMsgBatchReq)(nil),          // 29: lane.msg.SendMsgBatchReq
	(*msg.QueryMultiRoomPagesReq)(nil),   // 30: lane.msg.QueryMultiRoomPagesReq
	(*msg.QueryMultiRoomPagesReply)(nil), // 31: lane.msg.QueryMultiRoomPagesReply
}
var file_proto_logic_logic_proto_depIdxs = []int32{
	26, // 0: lane.logic.QueryRoomResp.roomids:type_name -> lane.logic.QueryRoomResp.RoomSlice
	27, // 1: lane.logic.QueryServerResp.userinfoResp:type_name -> lane.logic.QueryServerResp.UserInfoResp
	28, // 2: lane.logic.logic.SendMsg:input_type -> lane.msg.SendMsgReq
	29, // 3: lane.logic.logic.SendMsgBatch:input_type -> lane.msg.SendMsgBatchReq
	24, // 4: lane.logic.logic.QueryLast:input_type -> lane.logic.QueryLastReq
	30, // 5: lane.logic.logic.QueryStoreMsgBatch:input_type -> lane.msg.QueryMultiRoomPagesReq
	2,  // 6: lane.logic.logic.SetOnline:input_type -> lane.logic.SetOnlineReq
	4,  // 7: lane.logic.logic.SetOnlineBatch:input_type -> lane.logic.SetOnlineBatchReq
	6,  // 8: lane.logic.logic.SetOffline:input_type -> lane.logic.SetOfflineReq
	7,  // 9: lane.logic.logic.SetOfflineBatch:input_type -> lane.logic.SetOfflineBatchReq
	15, // 10: lane.logic.logic.NewUser:input_type -> lane.logic.NewUserReq
	17, // 11: lane.logic.logic.NewUserBatch:input_type -> lane.logic.NewUserBatchReq
	21, // 12: lane.logic.logic.DelUser:input_type -> lane.logic.DelUserReq
	19, // 13: lane.logic.logic.NewRoom:input_type -> lane.logic.NewRoomReq
	8,  // 14: lane.logic.logic.JoinRoom:input_type -> lane.logic.JoinRoomReq
	9,  // 15: lane.logic.logic.JoinRoomBatch:input_type -> lane.logic.JoinRoomBatchReq
	10, // 16: lane.logic.logic.QuitRoom:input_type -> lane.logic.QuitRoomReq
	11, // 17: lane.logic.logic.QueryRoom:input_type -> lane.logic.QueryRoomReq
	13, // 18: lane.logic.logic.QueryServer:input_type -> lane.logic.QueryServerReq
	22, // 19: lane.logic.logic.Auth:input_type -> lane.logic.AuthReq
	1,  // 20: lane.logic.logic.SendMsg:output_type -> lane.logic.NoResp
	1,  // 21: lane.logic.logic.SendMsgBatch:output_type -> lane.logic.NoResp
	25, // 22: lane.logic.logic.QueryLast:output_type -> lane.logic.QueryLastRelpy
	31, // 23: lane.logic.logic.QueryStoreMsgBatch:output_type -> lane.msg.QueryMultiRoomPagesReply
	1,  // 24: lane.logic.logic.SetOnline:output_type -> lane.logic.NoResp
	1,  // 25: lane.logic.logic.SetOnlineBatch:output_type -> lane.logic.NoResp
	1,  // 26: lane.logic.logic.SetOffline:output_type -> lane.logic.NoResp
	1,  // 27: lane.logic.logic.SetOfflineBatch:output_type -> lane.logic.NoResp
	16, // 28: lane.logic.logic.NewUser:output_type -> lane.logic.NewUserResp
	18, // 29: lane.logic.logic.NewUserBatch:output_type -> lane.logic.NewUserBatchResp
	1,  // 30: lane.logic.logic.DelUser:output_type -> lane.logic.NoResp
	20, // 31: lane.logic.logic.NewRoom:output_type -> lane.logic.NewRoomResp
	1,  // 32: lane.logic.logic.JoinRoom:output_type -> lane.logic.NoResp
	1,  // 33: lane.logic.logic.JoinRoomBatch:output_type -> lane.logic.NoResp
	1,  // 34: lane.logic.logic.QuitRoom:output_type -> lane.logic.NoResp
	12, // 35: lane.logic.logic.QueryRoom:output_type -> lane.logic.QueryRoomResp
	14, // 36: lane.logic.logic.QueryServer:output_type -> lane.logic.QueryServerResp
	23, // 37: lane.logic.logic.Auth:output_type -> lane.logic.AuthResp
	20, // [20:38] is the sub-list for method output_type
	2,  // [2:20] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_logic_logic_proto_init() }
func file_proto_logic_logic_proto_init() {
	if File_proto_logic_logic_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_logic_logic_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*NoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_logic_logic_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*NoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_logic_logic_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*SetOnlineReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_logic_logic_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*SetOnlineResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_logic_logic_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*SetOnlineBatchReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_logic_logic_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*SetOnlineBatchResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_logic_logic_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*SetOfflineReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_logic_logic_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*SetOfflineBatchReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_logic_logic_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*JoinRoomReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_logic_logic_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*JoinRoomBatchReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_logic_logic_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*QuitRoomReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_logic_logic_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*QueryRoomReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_logic_logic_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*QueryRoomResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_logic_logic_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*QueryServerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_logic_logic_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*QueryServerResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_logic_logic_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*NewUserReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_logic_logic_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*NewUserResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_logic_logic_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*NewUserBatchReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_logic_logic_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*NewUserBatchResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_logic_logic_proto_msgTypes[19].Exporter = func(v any, i int) any {
			switch v := v.(*NewRoomReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_logic_logic_proto_msgTypes[20].Exporter = func(v any, i int) any {
			switch v := v.(*NewRoomResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_logic_logic_proto_msgTypes[21].Exporter = func(v any, i int) any {
			switch v := v.(*DelUserReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_logic_logic_proto_msgTypes[22].Exporter = func(v any, i int) any {
			switch v := v.(*AuthReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_logic_logic_proto_msgTypes[23].Exporter = func(v any, i int) any {
			switch v := v.(*AuthResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_logic_logic_proto_msgTypes[24].Exporter = func(v any, i int) any {
			switch v := v.(*QueryLastReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_logic_logic_proto_msgTypes[25].Exporter = func(v any, i int) any {
			switch v := v.(*QueryLastRelpy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_logic_logic_proto_msgTypes[26].Exporter = func(v any, i int) any {
			switch v := v.(*QueryRoomResp_RoomSlice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_logic_logic_proto_msgTypes[27].Exporter = func(v any, i int) any {
			switch v := v.(*QueryServerResp_UserInfoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_logic_logic_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_logic_logic_proto_goTypes,
		DependencyIndexes: file_proto_logic_logic_proto_depIdxs,
		MessageInfos:      file_proto_logic_logic_proto_msgTypes,
	}.Build()
	File_proto_logic_logic_proto = out.File
	file_proto_logic_logic_proto_rawDesc = nil
	file_proto_logic_logic_proto_goTypes = nil
	file_proto_logic_logic_proto_depIdxs = nil
}
