// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: proto/logic/logic.proto

package logic

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	msg "laneIM/proto/msg"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SingleReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userid int64    `protobuf:"varint,1,opt,name=userid,proto3" json:"userid,omitempty"`
	Roomid int64    `protobuf:"varint,2,opt,name=roomid,proto3" json:"roomid,omitempty"`
	Msg    *msg.Msg `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *SingleReq) Reset() {
	*x = SingleReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_logic_logic_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SingleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleReq) ProtoMessage() {}

func (x *SingleReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_logic_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleReq.ProtoReflect.Descriptor instead.
func (*SingleReq) Descriptor() ([]byte, []int) {
	return file_proto_logic_logic_proto_rawDescGZIP(), []int{0}
}

func (x *SingleReq) GetUserid() int64 {
	if x != nil {
		return x.Userid
	}
	return 0
}

func (x *SingleReq) GetRoomid() int64 {
	if x != nil {
		return x.Roomid
	}
	return 0
}

func (x *SingleReq) GetMsg() *msg.Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

type SingleResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SingleResp) Reset() {
	*x = SingleResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_logic_logic_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SingleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleResp) ProtoMessage() {}

func (x *SingleResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_logic_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleResp.ProtoReflect.Descriptor instead.
func (*SingleResp) Descriptor() ([]byte, []int) {
	return file_proto_logic_logic_proto_rawDescGZIP(), []int{1}
}

type BrodcastReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg *msg.Msg `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *BrodcastReq) Reset() {
	*x = BrodcastReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_logic_logic_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BrodcastReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrodcastReq) ProtoMessage() {}

func (x *BrodcastReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_logic_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrodcastReq.ProtoReflect.Descriptor instead.
func (*BrodcastReq) Descriptor() ([]byte, []int) {
	return file_proto_logic_logic_proto_rawDescGZIP(), []int{2}
}

func (x *BrodcastReq) GetMsg() *msg.Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

type BrodcastResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BrodcastResp) Reset() {
	*x = BrodcastResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_logic_logic_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BrodcastResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrodcastResp) ProtoMessage() {}

func (x *BrodcastResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_logic_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrodcastResp.ProtoReflect.Descriptor instead.
func (*BrodcastResp) Descriptor() ([]byte, []int) {
	return file_proto_logic_logic_proto_rawDescGZIP(), []int{3}
}

type BrodcastRoomReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Roomid int64    `protobuf:"varint,1,opt,name=roomid,proto3" json:"roomid,omitempty"`
	Userid int64    `protobuf:"varint,2,opt,name=userid,proto3" json:"userid,omitempty"`
	Msg    *msg.Msg `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *BrodcastRoomReq) Reset() {
	*x = BrodcastRoomReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_logic_logic_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BrodcastRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrodcastRoomReq) ProtoMessage() {}

func (x *BrodcastRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_logic_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrodcastRoomReq.ProtoReflect.Descriptor instead.
func (*BrodcastRoomReq) Descriptor() ([]byte, []int) {
	return file_proto_logic_logic_proto_rawDescGZIP(), []int{4}
}

func (x *BrodcastRoomReq) GetRoomid() int64 {
	if x != nil {
		return x.Roomid
	}
	return 0
}

func (x *BrodcastRoomReq) GetUserid() int64 {
	if x != nil {
		return x.Userid
	}
	return 0
}

func (x *BrodcastRoomReq) GetMsg() *msg.Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

type BrodcastRoomResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BrodcastRoomResp) Reset() {
	*x = BrodcastRoomResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_logic_logic_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BrodcastRoomResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrodcastRoomResp) ProtoMessage() {}

func (x *BrodcastRoomResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_logic_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrodcastRoomResp.ProtoReflect.Descriptor instead.
func (*BrodcastRoomResp) Descriptor() ([]byte, []int) {
	return file_proto_logic_logic_proto_rawDescGZIP(), []int{5}
}

type NoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NoResp) Reset() {
	*x = NoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_logic_logic_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoResp) ProtoMessage() {}

func (x *NoResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_logic_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoResp.ProtoReflect.Descriptor instead.
func (*NoResp) Descriptor() ([]byte, []int) {
	return file_proto_logic_logic_proto_rawDescGZIP(), []int{6}
}

type SetOnlineReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Roomid int64 `protobuf:"varint,1,opt,name=roomid,proto3" json:"roomid,omitempty"`
	Userid int64 `protobuf:"varint,2,opt,name=userid,proto3" json:"userid,omitempty"`
}

func (x *SetOnlineReq) Reset() {
	*x = SetOnlineReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_logic_logic_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetOnlineReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetOnlineReq) ProtoMessage() {}

func (x *SetOnlineReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_logic_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetOnlineReq.ProtoReflect.Descriptor instead.
func (*SetOnlineReq) Descriptor() ([]byte, []int) {
	return file_proto_logic_logic_proto_rawDescGZIP(), []int{7}
}

func (x *SetOnlineReq) GetRoomid() int64 {
	if x != nil {
		return x.Roomid
	}
	return 0
}

func (x *SetOnlineReq) GetUserid() int64 {
	if x != nil {
		return x.Userid
	}
	return 0
}

type SetOnlineResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetOnlineResp) Reset() {
	*x = SetOnlineResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_logic_logic_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetOnlineResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetOnlineResp) ProtoMessage() {}

func (x *SetOnlineResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_logic_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetOnlineResp.ProtoReflect.Descriptor instead.
func (*SetOnlineResp) Descriptor() ([]byte, []int) {
	return file_proto_logic_logic_proto_rawDescGZIP(), []int{8}
}

type RoomReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Roomid int64 `protobuf:"varint,1,opt,name=roomid,proto3" json:"roomid,omitempty"`
}

func (x *RoomReq) Reset() {
	*x = RoomReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_logic_logic_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomReq) ProtoMessage() {}

func (x *RoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_logic_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomReq.ProtoReflect.Descriptor instead.
func (*RoomReq) Descriptor() ([]byte, []int) {
	return file_proto_logic_logic_proto_rawDescGZIP(), []int{9}
}

func (x *RoomReq) GetRoomid() int64 {
	if x != nil {
		return x.Roomid
	}
	return 0
}

type UserInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userid int64 `protobuf:"varint,1,opt,name=userid,proto3" json:"userid,omitempty"`
	Online bool  `protobuf:"varint,2,opt,name=online,proto3" json:"online,omitempty"`
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_logic_logic_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_logic_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_proto_logic_logic_proto_rawDescGZIP(), []int{10}
}

func (x *UserInfo) GetUserid() int64 {
	if x != nil {
		return x.Userid
	}
	return 0
}

func (x *UserInfo) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

type RoomResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userinfos []*UserInfo `protobuf:"bytes,1,rep,name=userinfos,proto3" json:"userinfos,omitempty"`
}

func (x *RoomResp) Reset() {
	*x = RoomResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_logic_logic_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomResp) ProtoMessage() {}

func (x *RoomResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_logic_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomResp.ProtoReflect.Descriptor instead.
func (*RoomResp) Descriptor() ([]byte, []int) {
	return file_proto_logic_logic_proto_rawDescGZIP(), []int{11}
}

func (x *RoomResp) GetUserinfos() []*UserInfo {
	if x != nil {
		return x.Userinfos
	}
	return nil
}

type SetOfflineReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userid int64 `protobuf:"varint,1,opt,name=userid,proto3" json:"userid,omitempty"`
}

func (x *SetOfflineReq) Reset() {
	*x = SetOfflineReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_logic_logic_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetOfflineReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetOfflineReq) ProtoMessage() {}

func (x *SetOfflineReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_logic_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetOfflineReq.ProtoReflect.Descriptor instead.
func (*SetOfflineReq) Descriptor() ([]byte, []int) {
	return file_proto_logic_logic_proto_rawDescGZIP(), []int{12}
}

func (x *SetOfflineReq) GetUserid() int64 {
	if x != nil {
		return x.Userid
	}
	return 0
}

type JoinRoomReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userid int64 `protobuf:"varint,1,opt,name=userid,proto3" json:"userid,omitempty"`
	Roomid int64 `protobuf:"varint,2,opt,name=roomid,proto3" json:"roomid,omitempty"`
}

func (x *JoinRoomReq) Reset() {
	*x = JoinRoomReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_logic_logic_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomReq) ProtoMessage() {}

func (x *JoinRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_logic_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomReq.ProtoReflect.Descriptor instead.
func (*JoinRoomReq) Descriptor() ([]byte, []int) {
	return file_proto_logic_logic_proto_rawDescGZIP(), []int{13}
}

func (x *JoinRoomReq) GetUserid() int64 {
	if x != nil {
		return x.Userid
	}
	return 0
}

func (x *JoinRoomReq) GetRoomid() int64 {
	if x != nil {
		return x.Roomid
	}
	return 0
}

type QuitRoomReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userid int64 `protobuf:"varint,1,opt,name=userid,proto3" json:"userid,omitempty"`
	Roomid int64 `protobuf:"varint,2,opt,name=roomid,proto3" json:"roomid,omitempty"`
}

func (x *QuitRoomReq) Reset() {
	*x = QuitRoomReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_logic_logic_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuitRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuitRoomReq) ProtoMessage() {}

func (x *QuitRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_logic_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuitRoomReq.ProtoReflect.Descriptor instead.
func (*QuitRoomReq) Descriptor() ([]byte, []int) {
	return file_proto_logic_logic_proto_rawDescGZIP(), []int{14}
}

func (x *QuitRoomReq) GetUserid() int64 {
	if x != nil {
		return x.Userid
	}
	return 0
}

func (x *QuitRoomReq) GetRoomid() int64 {
	if x != nil {
		return x.Roomid
	}
	return 0
}

var File_proto_logic_logic_proto protoreflect.FileDescriptor

var file_proto_logic_logic_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2f, 0x6c, 0x6f,
	0x67, 0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x6c, 0x61, 0x6e, 0x65, 0x2e,
	0x6c, 0x6f, 0x67, 0x69, 0x63, 0x1a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x73, 0x67,
	0x2f, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5c, 0x0a, 0x09, 0x53, 0x69,
	0x6e, 0x67, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x6d, 0x73, 0x67, 0x2e,
	0x4d, 0x73, 0x67, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x0c, 0x0a, 0x0a, 0x53, 0x69, 0x6e, 0x67,
	0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x2e, 0x0a, 0x0b, 0x42, 0x72, 0x6f, 0x64, 0x63, 0x61,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1f, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x4d, 0x73,
	0x67, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x0e, 0x0a, 0x0c, 0x42, 0x72, 0x6f, 0x64, 0x63, 0x61,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x22, 0x62, 0x0a, 0x0f, 0x42, 0x72, 0x6f, 0x64, 0x63, 0x61,
	0x73, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f,
	0x6d, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x69,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x03, 0x6d, 0x73, 0x67,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x6d, 0x73,
	0x67, 0x2e, 0x4d, 0x73, 0x67, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x12, 0x0a, 0x10, 0x42, 0x72,
	0x6f, 0x64, 0x63, 0x61, 0x73, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x22, 0x08,
	0x0a, 0x06, 0x4e, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x22, 0x3e, 0x0a, 0x0c, 0x53, 0x65, 0x74, 0x4f,
	0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x69, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x22, 0x0f, 0x0a, 0x0d, 0x53, 0x65, 0x74, 0x4f,
	0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x21, 0x0a, 0x07, 0x52, 0x6f, 0x6f,
	0x6d, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x69, 0x64, 0x22, 0x3a, 0x0a, 0x08,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x06, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x22, 0x3e, 0x0a, 0x08, 0x52, 0x6f, 0x6f, 0x6d,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x32, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x69, 0x6e, 0x66, 0x6f,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x6c,
	0x6f, 0x67, 0x69, 0x63, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x75,
	0x73, 0x65, 0x72, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x22, 0x27, 0x0a, 0x0d, 0x53, 0x65, 0x74, 0x4f,
	0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69,
	0x64, 0x22, 0x3d, 0x0a, 0x0b, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71,
	0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x69, 0x64,
	0x22, 0x3d, 0x0a, 0x0b, 0x51, 0x75, 0x69, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x12,
	0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x69, 0x64, 0x32,
	0xd3, 0x03, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x12, 0x33, 0x0a, 0x06, 0x53, 0x69, 0x6e,
	0x67, 0x6c, 0x65, 0x12, 0x15, 0x2e, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63,
	0x2e, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x6c, 0x61, 0x6e,
	0x65, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x4e, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x37,
	0x0a, 0x08, 0x42, 0x72, 0x6f, 0x64, 0x63, 0x61, 0x73, 0x74, 0x12, 0x17, 0x2e, 0x6c, 0x61, 0x6e,
	0x65, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x42, 0x72, 0x6f, 0x64, 0x63, 0x61, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63,
	0x2e, 0x4e, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3f, 0x0a, 0x0c, 0x42, 0x72, 0x6f, 0x64, 0x63,
	0x61, 0x73, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x1b, 0x2e, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x6c,
	0x6f, 0x67, 0x69, 0x63, 0x2e, 0x42, 0x72, 0x6f, 0x64, 0x63, 0x61, 0x73, 0x74, 0x52, 0x6f, 0x6f,
	0x6d, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x6c, 0x6f, 0x67, 0x69,
	0x63, 0x2e, 0x4e, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x39, 0x0a, 0x09, 0x53, 0x65, 0x74, 0x4f,
	0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x18, 0x2e, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x6c, 0x6f, 0x67,
	0x69, 0x63, 0x2e, 0x53, 0x65, 0x74, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x1a,
	0x12, 0x2e, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x4e, 0x6f, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x3b, 0x0a, 0x0a, 0x53, 0x65, 0x74, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e,
	0x65, 0x12, 0x19, 0x2e, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x53,
	0x65, 0x74, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x6c,
	0x61, 0x6e, 0x65, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x4e, 0x6f, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x37, 0x0a, 0x08, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x17, 0x2e, 0x6c,
	0x61, 0x6e, 0x65, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f,
	0x6f, 0x6d, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x6c, 0x6f, 0x67,
	0x69, 0x63, 0x2e, 0x4e, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x37, 0x0a, 0x08, 0x51, 0x75, 0x69,
	0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x17, 0x2e, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x6c, 0x6f, 0x67,
	0x69, 0x63, 0x2e, 0x51, 0x75, 0x69, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x1a, 0x12,
	0x2e, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x4e, 0x6f, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x31, 0x0a, 0x04, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x13, 0x2e, 0x6c, 0x61, 0x6e,
	0x65, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x1a,
	0x14, 0x2e, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x52, 0x6f, 0x6f,
	0x6d, 0x52, 0x65, 0x73, 0x70, 0x42, 0x1a, 0x5a, 0x18, 0x6c, 0x61, 0x6e, 0x65, 0x49, 0x4d, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x3b, 0x6c, 0x6f, 0x67, 0x69,
	0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_logic_logic_proto_rawDescOnce sync.Once
	file_proto_logic_logic_proto_rawDescData = file_proto_logic_logic_proto_rawDesc
)

func file_proto_logic_logic_proto_rawDescGZIP() []byte {
	file_proto_logic_logic_proto_rawDescOnce.Do(func() {
		file_proto_logic_logic_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_logic_logic_proto_rawDescData)
	})
	return file_proto_logic_logic_proto_rawDescData
}

var file_proto_logic_logic_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_logic_logic_proto_goTypes = []any{
	(*SingleReq)(nil),        // 0: lane.logic.SingleReq
	(*SingleResp)(nil),       // 1: lane.logic.SingleResp
	(*BrodcastReq)(nil),      // 2: lane.logic.BrodcastReq
	(*BrodcastResp)(nil),     // 3: lane.logic.BrodcastResp
	(*BrodcastRoomReq)(nil),  // 4: lane.logic.BrodcastRoomReq
	(*BrodcastRoomResp)(nil), // 5: lane.logic.BrodcastRoomResp
	(*NoResp)(nil),           // 6: lane.logic.NoResp
	(*SetOnlineReq)(nil),     // 7: lane.logic.SetOnlineReq
	(*SetOnlineResp)(nil),    // 8: lane.logic.SetOnlineResp
	(*RoomReq)(nil),          // 9: lane.logic.RoomReq
	(*UserInfo)(nil),         // 10: lane.logic.UserInfo
	(*RoomResp)(nil),         // 11: lane.logic.RoomResp
	(*SetOfflineReq)(nil),    // 12: lane.logic.SetOfflineReq
	(*JoinRoomReq)(nil),      // 13: lane.logic.JoinRoomReq
	(*QuitRoomReq)(nil),      // 14: lane.logic.QuitRoomReq
	(*msg.Msg)(nil),          // 15: lane.msg.Msg
}
var file_proto_logic_logic_proto_depIdxs = []int32{
	15, // 0: lane.logic.SingleReq.msg:type_name -> lane.msg.Msg
	15, // 1: lane.logic.BrodcastReq.msg:type_name -> lane.msg.Msg
	15, // 2: lane.logic.BrodcastRoomReq.msg:type_name -> lane.msg.Msg
	10, // 3: lane.logic.RoomResp.userinfos:type_name -> lane.logic.UserInfo
	0,  // 4: lane.logic.logic.Single:input_type -> lane.logic.SingleReq
	2,  // 5: lane.logic.logic.Brodcast:input_type -> lane.logic.BrodcastReq
	4,  // 6: lane.logic.logic.BrodcastRoom:input_type -> lane.logic.BrodcastRoomReq
	7,  // 7: lane.logic.logic.SetOnline:input_type -> lane.logic.SetOnlineReq
	12, // 8: lane.logic.logic.SetOffline:input_type -> lane.logic.SetOfflineReq
	13, // 9: lane.logic.logic.JoinRoom:input_type -> lane.logic.JoinRoomReq
	14, // 10: lane.logic.logic.QuitRoom:input_type -> lane.logic.QuitRoomReq
	9,  // 11: lane.logic.logic.Room:input_type -> lane.logic.RoomReq
	6,  // 12: lane.logic.logic.Single:output_type -> lane.logic.NoResp
	6,  // 13: lane.logic.logic.Brodcast:output_type -> lane.logic.NoResp
	6,  // 14: lane.logic.logic.BrodcastRoom:output_type -> lane.logic.NoResp
	6,  // 15: lane.logic.logic.SetOnline:output_type -> lane.logic.NoResp
	6,  // 16: lane.logic.logic.SetOffline:output_type -> lane.logic.NoResp
	6,  // 17: lane.logic.logic.JoinRoom:output_type -> lane.logic.NoResp
	6,  // 18: lane.logic.logic.QuitRoom:output_type -> lane.logic.NoResp
	11, // 19: lane.logic.logic.Room:output_type -> lane.logic.RoomResp
	12, // [12:20] is the sub-list for method output_type
	4,  // [4:12] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_logic_logic_proto_init() }
func file_proto_logic_logic_proto_init() {
	if File_proto_logic_logic_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_logic_logic_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SingleReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_logic_logic_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*SingleResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_logic_logic_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*BrodcastReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_logic_logic_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*BrodcastResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_logic_logic_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*BrodcastRoomReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_logic_logic_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*BrodcastRoomResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_logic_logic_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*NoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_logic_logic_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*SetOnlineReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_logic_logic_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*SetOnlineResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_logic_logic_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*RoomReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_logic_logic_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*UserInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_logic_logic_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*RoomResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_logic_logic_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*SetOfflineReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_logic_logic_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*JoinRoomReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_logic_logic_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*QuitRoomReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_logic_logic_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_logic_logic_proto_goTypes,
		DependencyIndexes: file_proto_logic_logic_proto_depIdxs,
		MessageInfos:      file_proto_logic_logic_proto_msgTypes,
	}.Build()
	File_proto_logic_logic_proto = out.File
	file_proto_logic_logic_proto_rawDesc = nil
	file_proto_logic_logic_proto_goTypes = nil
	file_proto_logic_logic_proto_depIdxs = nil
}
