addr: 127.0.0.1:50070
name: "0"
kafkacomsumer:
  addr:
    - 127.0.0.1:9092
  topics:
    - laneIM
  groupid: job
etcd:
  addr:
    - 127.0.0.1:2379
redis:
  addr:
    - 127.0.0.1:7001
    - 127.0.0.1:7002
    - 127.0.0.1:7003
bucketsize: 32
cometroutinesize: 32
mysql:
  type: ""
  name: "0"
  username: root
  password: 123456
  addr: 120.78.234.30:3306
  database: laneIM
