addr: 127.0.0.1:50070
name: "0"
kafkacomsumer:
  addr:
    - 127.0.0.1:9092
  topics:
    - laneIM
  groupid: job
etcd:
  addr:
    - 127.0.0.1:51240
    - 127.0.0.1:51241
    - 127.0.0.1:51242
redis:
  addr:
    - 127.0.0.1:7001
    - 127.0.0.1:7002
    - 127.0.0.1:7003
bucketsize: 32
cometroutinesize: 32
mysql:
  type: ""
  name: "0"
  username: debian-sys-maint
  password: FJho5xokpFqZygL5
  addr: 127.0.0.1:3306
  database: laneIM
  batchwriter:
    maxtime: 100
    maxcount: 1000
