// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: proto/comet/comet.proto

package comet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	msg "laneIM/proto/msg"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SingleReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userid int64  `protobuf:"varint,1,opt,name=userid,proto3" json:"userid,omitempty"`
	Roomid int64  `protobuf:"varint,2,opt,name=roomid,proto3" json:"roomid,omitempty"`
	Data   []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SingleReq) Reset() {
	*x = SingleReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_comet_comet_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SingleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleReq) ProtoMessage() {}

func (x *SingleReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comet_comet_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleReq.ProtoReflect.Descriptor instead.
func (*SingleReq) Descriptor() ([]byte, []int) {
	return file_proto_comet_comet_proto_rawDescGZIP(), []int{0}
}

func (x *SingleReq) GetUserid() int64 {
	if x != nil {
		return x.Userid
	}
	return 0
}

func (x *SingleReq) GetRoomid() int64 {
	if x != nil {
		return x.Roomid
	}
	return 0
}

func (x *SingleReq) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SingleResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SingleResp) Reset() {
	*x = SingleResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_comet_comet_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SingleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleResp) ProtoMessage() {}

func (x *SingleResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comet_comet_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleResp.ProtoReflect.Descriptor instead.
func (*SingleResp) Descriptor() ([]byte, []int) {
	return file_proto_comet_comet_proto_rawDescGZIP(), []int{1}
}

type BrodcastReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *BrodcastReq) Reset() {
	*x = BrodcastReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_comet_comet_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BrodcastReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrodcastReq) ProtoMessage() {}

func (x *BrodcastReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comet_comet_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrodcastReq.ProtoReflect.Descriptor instead.
func (*BrodcastReq) Descriptor() ([]byte, []int) {
	return file_proto_comet_comet_proto_rawDescGZIP(), []int{2}
}

func (x *BrodcastReq) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type BrodcastResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BrodcastResp) Reset() {
	*x = BrodcastResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_comet_comet_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BrodcastResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrodcastResp) ProtoMessage() {}

func (x *BrodcastResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comet_comet_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrodcastResp.ProtoReflect.Descriptor instead.
func (*BrodcastResp) Descriptor() ([]byte, []int) {
	return file_proto_comet_comet_proto_rawDescGZIP(), []int{3}
}

type RoomReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Roomid int64  `protobuf:"varint,1,opt,name=roomid,proto3" json:"roomid,omitempty"`
	Data   []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *RoomReq) Reset() {
	*x = RoomReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_comet_comet_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomReq) ProtoMessage() {}

func (x *RoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comet_comet_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomReq.ProtoReflect.Descriptor instead.
func (*RoomReq) Descriptor() ([]byte, []int) {
	return file_proto_comet_comet_proto_rawDescGZIP(), []int{4}
}

func (x *RoomReq) GetRoomid() int64 {
	if x != nil {
		return x.Roomid
	}
	return 0
}

func (x *RoomReq) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type RoomResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RoomResp) Reset() {
	*x = RoomResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_comet_comet_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomResp) ProtoMessage() {}

func (x *RoomResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comet_comet_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomResp.ProtoReflect.Descriptor instead.
func (*RoomResp) Descriptor() ([]byte, []int) {
	return file_proto_comet_comet_proto_rawDescGZIP(), []int{5}
}

type NoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NoResp) Reset() {
	*x = NoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_comet_comet_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoResp) ProtoMessage() {}

func (x *NoResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comet_comet_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoResp.ProtoReflect.Descriptor instead.
func (*NoResp) Descriptor() ([]byte, []int) {
	return file_proto_comet_comet_proto_rawDescGZIP(), []int{6}
}

var File_proto_comet_comet_proto protoreflect.FileDescriptor

var file_proto_comet_comet_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x65, 0x74, 0x2f, 0x63, 0x6f,
	0x6d, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x6c, 0x61, 0x6e, 0x65, 0x2e,
	0x63, 0x6f, 0x6d, 0x65, 0x74, 0x1a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x73, 0x67,
	0x2f, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4f, 0x0a, 0x09, 0x53, 0x69,
	0x6e, 0x67, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x0c, 0x0a, 0x0a, 0x53,
	0x69, 0x6e, 0x67, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x21, 0x0a, 0x0b, 0x42, 0x72, 0x6f,
	0x64, 0x63, 0x61, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x0e, 0x0a, 0x0c,
	0x42, 0x72, 0x6f, 0x64, 0x63, 0x61, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x22, 0x35, 0x0a, 0x07,
	0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x0a, 0x0a, 0x08, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x22,
	0x08, 0x0a, 0x06, 0x4e, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x32, 0xb4, 0x01, 0x0a, 0x05, 0x63, 0x6f,
	0x6d, 0x65, 0x74, 0x12, 0x33, 0x0a, 0x06, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x12, 0x15, 0x2e,
	0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x63, 0x6f, 0x6d, 0x65, 0x74, 0x2e, 0x53, 0x69, 0x6e, 0x67, 0x6c,
	0x65, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x63, 0x6f, 0x6d, 0x65,
	0x74, 0x2e, 0x4e, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x37, 0x0a, 0x08, 0x42, 0x72, 0x6f, 0x64,
	0x63, 0x61, 0x73, 0x74, 0x12, 0x17, 0x2e, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x63, 0x6f, 0x6d, 0x65,
	0x74, 0x2e, 0x42, 0x72, 0x6f, 0x64, 0x63, 0x61, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e,
	0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x63, 0x6f, 0x6d, 0x65, 0x74, 0x2e, 0x4e, 0x6f, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x3d, 0x0a, 0x0c, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x73, 0x67, 0x42, 0x61, 0x74, 0x63,
	0x68, 0x12, 0x19, 0x2e, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x53, 0x65, 0x6e,
	0x64, 0x4d, 0x73, 0x67, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x6c,
	0x61, 0x6e, 0x65, 0x2e, 0x63, 0x6f, 0x6d, 0x65, 0x74, 0x2e, 0x4e, 0x6f, 0x52, 0x65, 0x73, 0x70,
	0x42, 0x1a, 0x5a, 0x18, 0x6c, 0x61, 0x6e, 0x65, 0x49, 0x4d, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x63, 0x6f, 0x6d, 0x65, 0x74, 0x3b, 0x63, 0x6f, 0x6d, 0x65, 0x74, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_comet_comet_proto_rawDescOnce sync.Once
	file_proto_comet_comet_proto_rawDescData = file_proto_comet_comet_proto_rawDesc
)

func file_proto_comet_comet_proto_rawDescGZIP() []byte {
	file_proto_comet_comet_proto_rawDescOnce.Do(func() {
		file_proto_comet_comet_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_comet_comet_proto_rawDescData)
	})
	return file_proto_comet_comet_proto_rawDescData
}

var file_proto_comet_comet_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_comet_comet_proto_goTypes = []any{
	(*SingleReq)(nil),           // 0: lane.comet.SingleReq
	(*SingleResp)(nil),          // 1: lane.comet.SingleResp
	(*BrodcastReq)(nil),         // 2: lane.comet.BrodcastReq
	(*BrodcastResp)(nil),        // 3: lane.comet.BrodcastResp
	(*RoomReq)(nil),             // 4: lane.comet.RoomReq
	(*RoomResp)(nil),            // 5: lane.comet.RoomResp
	(*NoResp)(nil),              // 6: lane.comet.NoResp
	(*msg.SendMsgBatchReq)(nil), // 7: lane.msg.SendMsgBatchReq
}
var file_proto_comet_comet_proto_depIdxs = []int32{
	0, // 0: lane.comet.comet.Single:input_type -> lane.comet.SingleReq
	2, // 1: lane.comet.comet.Brodcast:input_type -> lane.comet.BrodcastReq
	7, // 2: lane.comet.comet.SendMsgBatch:input_type -> lane.msg.SendMsgBatchReq
	6, // 3: lane.comet.comet.Single:output_type -> lane.comet.NoResp
	6, // 4: lane.comet.comet.Brodcast:output_type -> lane.comet.NoResp
	6, // 5: lane.comet.comet.SendMsgBatch:output_type -> lane.comet.NoResp
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_comet_comet_proto_init() }
func file_proto_comet_comet_proto_init() {
	if File_proto_comet_comet_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_comet_comet_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SingleReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_comet_comet_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*SingleResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_comet_comet_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*BrodcastReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_comet_comet_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*BrodcastResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_comet_comet_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*RoomReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_comet_comet_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*RoomResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_comet_comet_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*NoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_comet_comet_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_comet_comet_proto_goTypes,
		DependencyIndexes: file_proto_comet_comet_proto_depIdxs,
		MessageInfos:      file_proto_comet_comet_proto_msgTypes,
	}.Build()
	File_proto_comet_comet_proto = out.File
	file_proto_comet_comet_proto_rawDesc = nil
	file_proto_comet_comet_proto_goTypes = nil
	file_proto_comet_comet_proto_depIdxs = nil
}
